### PR TITLE
feat!: Added color palette and font. Added navbar.

### PR DESCRIPTION
**Pull request by AaronHo-0716**
Installed ShadCn, configured tailwind css for the project's color palette.
Added a navbar.
image

### CODE REVIEW

**Review by satel33 — CHANGES_REQUESTED** [review]
Goog first work. 
- Change the file Logo filename into logo.svg
- Use Component name as CamelCase navbar.tsx => Navbar.tsx

Thanks

**Comment by AaronHo-0716** [comment]
Updated the code

**Comment by satel33** [comment]
Add screenshot of current looking and change of your work in the PR's description

**Review by satel33 — APPROVED** [review]
THanks for quick update

**Comment by AaronHo-0716** [comment]
image

**Pull request merged**
